version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extswap-nextjs-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    env_file:
      - .env.production

  nginx:
    image: nginx:alpine
    container_name: extswap-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
